body:
  - type: markdown
    attributes:
      value: |
        ### Hi, thanks for using LinkAce!
        Before starting to write this discussion, please follow the [**Troubleshooting Guide**](https://www.linkace.org/docs/v2/general/troubleshooting/) to find out more about your problem, as well as common issues encountered while running LinkAce.
        ### Disclaimer
        As written in the Readme of the project and on the website: I built LinkAce to solve my problem, and I now share my solution and code to your without charging anything. I spent a lot of my free time building this application already, so I won't offer any *free* personal support, customization or installation help.
  - type: textarea
    id: issue
    attributes:
      label: Describe your issue
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Troubleshooting
      options:
        - label: I have read the troubleshooting guide
          required: true
        - label: I have searched the community discussions for similar issues
          required: true
